name: ExtraEndPortals
version: '1.1'
main: me.twostinkysocks.extraendportals.ExtraEndPortals
author: 2stinkysocks
api-version: 1.21.4
commands:
  endportals:
    permission: endportals.reload
    usage: /<command>
permissions:
  endportals.reload:
    description: Reload the plugin
    default: false